import httpx
from biomedcat.config import settings

# Note: We no longer need torch, transformers, or bitsandbytes here 
# because the LLM is managed externally by Ollama.

def free_gpu() -> None:
    """
    Dummy function to maintain compatibility with existing pipeline stages.
    Since Ollama manages its own VRAM, there is nothing to free in this process.
    """
    pass

def build_llm():
    """
    Prepares the metadata for the LLM connection.
    Instead of loading weights into VRAM, we simply return the model identifier
    to be used by the Ollame API client.
    
    Returns:
        tuple: (None, model_id) where None represents the unused tokenizer 
               and model_id is the string name of the Ollama model.
    """
    # We return None for the tokenizer because Ollama handles templating internally.
    # The 'model' variable will now hold the string ID of the model to call.
    return (None, settings.llm_model_id)

def generate(model, tokenizer, messages: list[dict[str, str]], max_new_tokens: int) -> str:
    """
    Sends a chat request to the Ollama API and returns the generated text.
    
    Args:
        model (str): The name of the model to use in Ollama (e.g., 'llama3.1').
        tokenizer (None): Placeholder for compatibility; not used with Ollama API.
        messages (list[dict]): The list of chat messages (role/content).
        max_new_tokens (int): The maximum number of tokens to generate (mapped to num_predict).

    Returns:
        str: The text content generated by the model.
    """
    # Construct the Ollama API endpoint URL
    url = f"{settings.ollama_url}/api/chat"
    
    # Prepare the payload for the /api/chat endpoint
    payload = {
        "model": model,
        "messages": messages,
        "stream": False,  # We use non-streaming mode to match the original synchronous behavior
        "options": {
            "num_predict": max_new_tokens
        }
    }

    try:
        with httpx.Client(timeout=120.0) as client:
            response = client.post(url, json=payload)
            response.raise_for_status()
            
            # Extract the content from the Ollama response structure
            result = response.json()
            return result.get("message", {}).get("content", "").strip()
            
    except httpx.HTTPStatusError as e:
        raise RuntimeError(f"Ollama API error: {e.response.status_code} - {e.response.text}")
    except Exception as e:
        raise RuntimeError(f"Failed to communicate with Ollama at {settings.ollama_url}: {str(e)}")
