#!/usr/bin/env python
"""Build the exemplar leg's index from real KG2c node names, stratified per Biolink class.

data/biolink_exemplars.parquet (columns class, exemplar[, form, depth, parent]) feeds the
"mention-to-mention" leg of the RAG retriever (biomedcat.stages.rag_engine._load_exemplars):
short surface forms that a definition-only index cannot match well, fused by reciprocal rank
with the dense and sparse legs. That file was previously generated by an LLM one class at a
time (canonical / abbreviation / variant / compound), which risks inventing mentions that do
not occur in the graph the pipeline actually links against, and cannot be re-derived without
an LLM call per class.

This script draws exemplars directly from data/kg2c/nodes.parquet (`name`) and
data/kg2c/node_details.parquet (`synonyms`) instead: every sampled mention is a real KG2c
node name or one of its recorded synonyms, so the exemplar leg is anchored in the same
reference the linking stage will query afterwards. Sampling is stratified per Biolink class
(one draw per category, not per node) so common categories (Gene, SmallMolecule, ...) do not
crowd out rare ones, capped at --target-per-class per class.

Only classes whose Biolink name maps to a category actually present in KG2c can be sampled
this way (52 of ~145 non-deprecated, non-abstract classes at kg2c-2.10.1 — checked at the time
of writing). For the rest (statistical/study-result classes, dataset classes, etc. that KG2c
does not instantiate) there is no real node to draw from; pass --existing to carry their rows
over unchanged from a previous (e.g. LLM-generated) exemplars file, so the RAG index does not
lose coverage for those classes. Without --existing they are simply absent from the output,
and the exemplar leg falls back to the dense+sparse legs for them.

Usage (from the BiomedCAT root):
  uv run python scripts/build_biolink_exemplars.py
  uv run python scripts/build_biolink_exemplars.py --existing data/biolink_exemplars.parquet --out data/biolink_exemplars.parquet
  uv run python scripts/build_biolink_exemplars.py --target-per-class 40 --dry-run
"""
from __future__ import annotations

import argparse
import logging
import random
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pandas as pd
import pyarrow.parquet as pq

from biomedcat.weights import camel_curie  # 'small molecule' -> 'biolink:SmallMolecule'

logger = logging.getLogger("build_biolink_exemplars")

RANDOM_SEED = 77
MAX_WORDS = 6          # drops sentence-like KG2c names/synonyms, keeps multi-word compounds
MAX_CHARS = 60
ABBREV_MAX_LEN = 6      # short + all-caps single token: 'DM', 'TB', 'RTKs'


def _word_count(text: str) -> int:
    return len(text.split())


def _is_usable(text: str) -> bool:
    text = (text or "").strip()
    if not text or len(text) > MAX_CHARS:
        return False
    return 1 <= _word_count(text) <= MAX_WORDS


def _classify_form(text: str, is_canonical: bool) -> str:
    if is_canonical:
        return "canonical"
    token = text.strip()
    if len(token) <= ABBREV_MAX_LEN and token == token.upper() and token.isalpha():
        return "abbreviation"
    if _word_count(token) >= 3:
        return "compound"
    return "variant"


def _load_classes(path: Path) -> dict[str, dict[str, Any]]:
    import json
    flat = json.loads(path.read_text(encoding="utf-8"))
    out = {}
    for name, entry in flat.items():
        meta = entry.get("metadata", {})
        if meta.get("deprecated") or meta.get("abstract"):
            continue
        out[name] = {
            "depth": len(meta.get("ancestors") or []),
            "parent": meta.get("parent") or "",
        }
    return out


def _sample_class(
    class_name: str,
    class_info: dict[str, Any],
    nodes: pd.DataFrame,
    node_details: pd.DataFrame,
    target: int,
    max_synonyms_per_node: int,
    rng: random.Random,
) -> list[dict[str, Any]]:
    """Draw up to `target` real exemplars (names + synonyms) for one Biolink class."""
    category = camel_curie(class_name)
    pool = nodes.loc[nodes["category"] == category, ["id", "name"]]
    pool = pool[pool["name"].map(_is_usable)]
    if pool.empty:
        return []

    # Stratified draw: one canonical name per sampled node, so the sample spans distinct
    # concepts of the category rather than clustering on nodes with many synonyms.
    ids = pool["id"].tolist()
    rng.shuffle(ids)
    seen_casefold: set[str] = set()
    rows: list[dict[str, Any]] = []
    id_to_name = dict(zip(pool["id"], pool["name"]))

    for node_id in ids:
        if len(rows) >= target:
            break
        name = id_to_name[node_id]
        key = name.casefold()
        if key in seen_casefold:
            continue
        seen_casefold.add(key)
        rows.append({"class": class_name, "exemplar": name, "form": "canonical",
                      "depth": class_info["depth"], "parent": class_info["parent"], "_node_id": node_id})

    # Fill the remainder with synonyms of the nodes just drawn (real, recorded alternate
    # names), before falling back to more nodes if synonyms run out.
    if len(rows) < target and node_details is not None:
        sampled_ids = [r["_node_id"] for r in rows]
        syn = node_details.loc[node_details["id"].isin(sampled_ids), ["id", "synonyms"]]
        pairs: list[tuple[str, str]] = []
        for node_id, synonyms in zip(syn["id"], syn["synonyms"]):
            if synonyms is None:
                continue
            for s in list(synonyms)[:max_synonyms_per_node]:
                pairs.append((node_id, s))
        rng.shuffle(pairs)
        for node_id, s in pairs:
            if len(rows) >= target:
                break
            if not _is_usable(s):
                continue
            key = s.strip().casefold()
            if key in seen_casefold:
                continue
            seen_casefold.add(key)
            rows.append({"class": class_name, "exemplar": s.strip(), "form": _classify_form(s, is_canonical=False),
                         "depth": class_info["depth"], "parent": class_info["parent"], "_node_id": node_id})

    # Below `target` here means the category pool itself is small (fewer usable names+synonyms
    # than the target) — reported by the caller as an under-covered class, not filled further.
    for r in rows:
        r.pop("_node_id", None)
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--kg2c-dir", default=str(ROOT / "data/kg2c"))
    parser.add_argument("--classes", default=str(ROOT / "data/biolink_classes_flat.json"))
    parser.add_argument("--existing", default=None, help="Prior exemplars parquet to carry over rows for classes with no KG2c coverage.")
    parser.add_argument("--out", default=str(ROOT / "data/biolink_exemplars.parquet"))
    parser.add_argument("--target-per-class", type=int, default=30)
    parser.add_argument("--min-per-class", type=int, default=8, help="Below this, the class is reported as under-covered.")
    parser.add_argument("--max-synonyms-per-node", type=int, default=2)
    parser.add_argument("--seed", type=int, default=RANDOM_SEED)
    parser.add_argument("--dry-run", action="store_true", help="Print the report without writing the output file.")
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    kg2c_dir = Path(args.kg2c_dir)
    classes = _load_classes(Path(args.classes))
    logger.info("[*] %d non-deprecated, non-abstract Biolink classes", len(classes))

    nodes = pq.read_table(kg2c_dir / "nodes.parquet", columns=["id", "name", "category"]).to_pandas()
    nodes["category"] = nodes["category"].astype(str)
    details_path = kg2c_dir / "node_details.parquet"
    node_details = pq.read_table(details_path, columns=["id", "synonyms"]).to_pandas() if details_path.is_file() else None
    present_categories = set(nodes["category"].unique())

    rng = random.Random(args.seed)
    all_rows: list[dict[str, Any]] = []
    matched, under_covered, unmatched = [], [], []

    for class_name, info in sorted(classes.items()):
        category = camel_curie(class_name)
        if category not in present_categories:
            unmatched.append(class_name)
            continue
        rows = _sample_class(class_name, info, nodes, node_details, args.target_per_class,
                              args.max_synonyms_per_node, random.Random(rng.random()))
        if not rows:
            unmatched.append(class_name)
            continue
        matched.append((class_name, len(rows)))
        if len(rows) < args.min_per_class:
            under_covered.append((class_name, len(rows)))
        all_rows.extend(rows)

    carried_over = []
    if args.existing and Path(args.existing).is_file():
        existing = pq.read_table(args.existing).to_pandas()
        matched_names = {c for c, _ in matched}
        carry = existing[existing["class"].isin(unmatched) & ~existing["class"].isin(matched_names)]
        if not carry.empty:
            all_rows.extend(carry.to_dict("records"))
            carried_over = sorted(carry["class"].unique().tolist())
            unmatched = [c for c in unmatched if c not in carried_over]

    df = pd.DataFrame(all_rows, columns=["class", "exemplar", "form", "depth", "parent"])
    df = df.sort_values(["class", "form", "exemplar"], kind="stable").reset_index(drop=True)

    print(f"\n[*] Classes matched to a real KG2c category : {len(matched)}")
    print(f"[*] Classes carried over from --existing      : {len(carried_over)} {carried_over[:10]}{'...' if len(carried_over) > 10 else ''}")
    print(f"[*] Classes with no exemplar (no KG2c, no --existing fallback): {len(unmatched)}")
    if unmatched:
        print(f"    {unmatched[:15]}{'...' if len(unmatched) > 15 else ''}")
    if under_covered:
        print(f"[!] {len(under_covered)} classes below --min-per-class={args.min_per_class}:")
        for name, n in under_covered:
            print(f"    {name}: {n}")
    print(f"\n[*] Total rows: {len(df)} across {df['class'].nunique()} classes")
    print(df["form"].value_counts().to_string())

    if args.dry_run:
        print("\n[dry-run] Not writing output.")
        return 0

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(out_path, engine="pyarrow", index=False)
    print(f"\n[+] Wrote {out_path} ({len(df)} rows).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
